export type Buyer = {
    id: string;
    name: string;
    webhook_url: string;
    manual_send: boolean;
    worker_send: boolean;
    priority: number;
    auto_send: boolean;
    allow_resell: boolean;
    requires_validation: boolean;
    min_minutes_between_sends: number;
    max_minutes_between_sends: number;
    next_send_at: string | null;
    last_send_at: string | null;
    total_sends: number;
    auth_header_name: string;
    auth_header_prefix: string | null;
    auth_token_encrypted: string | null;
    blocked_affiliate_ids: string[];
    states_on_hold: string[];
    delay_same_county: number;
    delay_same_state: number;
    enforce_county_cooldown: boolean;
    enforce_state_cooldown: boolean;
    payload_format: 'default' | 'northstar';
    send_lead_id: boolean;
    send_private_note: boolean;
    on_hold: boolean;
    created: string;
    modified: string;
    deleted: string | null;
};

export type BuyerCreateDTO = {
    name: string;
    webhook_url: string;
    manual_send?: boolean;
    worker_send?: boolean;
    priority: number;
    auto_send?: boolean;
    allow_resell?: boolean;
    requires_validation?: boolean;
    min_minutes_between_sends?: number;
    max_minutes_between_sends?: number;
    auth_header_name?: string;
    auth_header_prefix?: string | null;
    auth_token?: string | null;
    blocked_affiliate_ids?: string[];
    states_on_hold?: string[];
    delay_same_county?: number;
    delay_same_state?: number;
    enforce_county_cooldown?: boolean;
    enforce_state_cooldown?: boolean;
    payload_format?: 'default' | 'northstar';
    send_lead_id?: boolean;
    send_private_note?: boolean;
};

export type BuyerUpdateDTO = {
    name?: string;
    webhook_url?: string;
    manual_send?: boolean;
    worker_send?: boolean;
    priority?: number;
    auto_send?: boolean;
    allow_resell?: boolean;
    requires_validation?: boolean;
    min_minutes_between_sends?: number;
    max_minutes_between_sends?: number;
    next_send_at?: string;
    auth_header_name?: string;
    auth_header_prefix?: string | null;
    auth_token?: string | null;
    blocked_affiliate_ids?: string[];
    states_on_hold?: string[];
    delay_same_county?: number;
    delay_same_state?: number;
    enforce_county_cooldown?: boolean;
    enforce_state_cooldown?: boolean;
    payload_format?: 'default' | 'northstar';
    send_lead_id?: boolean;
    send_private_note?: boolean;
};
