CREATE TABLE public."users" (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL,
  encrypted_password VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL DEFAULT 'user',
  created TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  modified TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  deleted TIMESTAMP WITH TIME ZONE
);

DELETE FROM buyers;