import { injectable } from "tsyringe";
import { IDatabase } from 'pg-promise';
import { DBContainer } from "../config/DBContainer";
import { Source, SourceCreateDTO, SourceUpdateDTO, SourceFilters } from "../types/sourceTypes";
import { IClient } from "pg-promise/typescript/pg-subset";

/**
 * SourceDAO - Data Access Layer for sources table
 * TICKET-046: Handles CRUD operations for lead sources with API authentication
 *
 * Token Storage: Plaintext (not encrypted)
 * Justification: 64-character hex tokens (256 bits entropy) are cryptographically
 * secure random values that don't benefit from encryption. Hashing would prevent
 * validation. Industry standard (Stripe, GitHub) stores API keys in plaintext.
 */
@injectable()
export default class SourceDAO {
    private readonly db: IDatabase<IClient>;

    constructor(db: DBContainer) {
        this.db = db.database();
    }

    /**
     * Check if a token already exists in the database
     * Used during token generation to ensure uniqueness
     */
    async tokenExists(token: string): Promise<boolean> {
        const query = `
            SELECT EXISTS(
                SELECT 1
                FROM sources
                WHERE token = $[token]
            ) as exists;
        `;

        const result = await this.db.one<{ exists: boolean }>(query, { token });
        return result.exists;
    }

    /**
     * Get source by token (for authentication)
     * Excludes soft-deleted sources - deleted token immediately fails auth
     */
    async getByToken(token: string): Promise<Source | null> {
        const query = `
            SELECT *
            FROM sources
            WHERE token = $[token]
                AND deleted IS NULL
            LIMIT 1;
        `;

        return await this.db.oneOrNone<Source>(query, { token });
    }

    /**
     * Get source by ID
     * Excludes soft-deleted sources
     */
    async getById(id: string): Promise<Source | null> {
        const query = `
            SELECT *
            FROM sources
            WHERE id = $[id]
                AND deleted IS NULL;
        `;

        return await this.db.oneOrNone<Source>(query, { id });
    }

    /**
     * Get all sources with pagination and filters
     */
    async getAll(filters: SourceFilters): Promise<{ items: Source[]; count: number }> {
        const { page, limit, search, includeDeleted } = filters;
        const offset = (page - 1) * limit;

        const whereClauses: string[] = [];

        if (!includeDeleted) {
            whereClauses.push('s.deleted IS NULL');
        }

        if (search) {
            whereClauses.push(`s.name ILIKE '%' || $/search/ || '%'`);
        }

        const whereSQL = whereClauses.length > 0 ? 'WHERE ' + whereClauses.join(' AND ') : '';

        const countWhereClauses: string[] = [];
        if (!includeDeleted) countWhereClauses.push('deleted IS NULL');
        if (search) countWhereClauses.push(`name ILIKE '%' || $/search/ || '%'`);
        const countWhereSQL = countWhereClauses.length > 0 ? 'WHERE ' + countWhereClauses.join(' AND ') : '';

        const itemsQuery = `
            SELECT s.*,
                lm.name AS lead_manager_name,
                COUNT(c.id)::int AS campaign_count
            FROM sources s
            LEFT JOIN lead_managers lm ON s.lead_manager_id = lm.id AND lm.deleted IS NULL
            LEFT JOIN campaigns c ON c.source_id = s.id AND c.deleted IS NULL
            ${whereSQL}
            GROUP BY s.id, lm.name
            ORDER BY s.created DESC
            LIMIT $/limit/ OFFSET $/offset/;
        `;

        const countQuery = `
            SELECT COUNT(*) as count
            FROM sources
            ${countWhereSQL};
        `;

        const [items, countResult] = await Promise.all([
            this.db.manyOrNone<Source>(itemsQuery, { ...filters, offset }),
            this.db.one<{ count: string }>(countQuery, filters)
        ]);

        return {
            items: items || [],
            count: parseInt(countResult.count, 10)
        };
    }

    /**
     * Create new source with token
     * Token must be generated by service before calling this method
     */
    async create(data: SourceCreateDTO & { token: string }): Promise<Source> {
        const query = `
            INSERT INTO sources (name, token)
            VALUES ($[name], $[token])
            RETURNING *;
        `;

        return await this.db.one<Source>(query, data);
    }

    /**
     * Update existing source
     * Only updates fields that are provided (not undefined)
     */
    async update(id: string, data: SourceUpdateDTO | { token: string }): Promise<Source> {
        // Get existing source to merge with updates
        const existing = await this.getById(id);
        if (!existing) {
            throw new Error('Source not found');
        }

        const query = `
            UPDATE sources
            SET
                name = $[name],
                token = $[token],
                lead_manager_id = $[lead_manager_id],
                modified = NOW()
            WHERE id = $[id]
                AND deleted IS NULL
            RETURNING *;
        `;

        // Merge with existing values - only update what's provided
        const updateData = {
            id,
            name: 'name' in data ? data.name : existing.name,
            token: 'token' in data ? data.token : existing.token,
            lead_manager_id: 'lead_manager_id' in data ? (data as SourceUpdateDTO).lead_manager_id ?? null : existing.lead_manager_id ?? null
        };

        return await this.db.one<Source>(query, updateData);
    }

    /**
     * Soft delete source
     * Sets deleted timestamp - immediately fails authentication
     */
    async trash(id: string): Promise<Source> {
        const query = `
            UPDATE sources
            SET deleted = NOW()
            WHERE id = $[id]
                AND deleted IS NULL
            RETURNING *;
        `;

        return await this.db.one<Source>(query, { id });
    }

    /**
     * Hard delete source (use with caution)
     * Should only be used for cleanup/testing
     */
    async delete(id: string): Promise<void> {
        const query = `
            DELETE FROM sources
            WHERE id = $[id];
        `;

        await this.db.none(query, { id });
    }
}
