import { injectable } from "tsyringe";
import { IDatabase } from 'pg-promise';
import { DBContainer } from "../config/DBContainer";
import { Source, SourceCreateDTO, SourceUpdateDTO, SourceFilters } from "../types/sourceTypes";
import { IClient } from "pg-promise/typescript/pg-subset";

/**
 * SourceDAO - Data Access Layer for sources table
 * TICKET-046: Handles CRUD operations for lead sources with API authentication
 *
 * Token Storage: Plaintext (not encrypted)
 * Justification: 64-character hex tokens (256 bits entropy) are cryptographically
 * secure random values that don't benefit from encryption. Hashing would prevent
 * validation. Industry standard (Stripe, GitHub) stores API keys in plaintext.
 */
@injectable()
export default class SourceDAO {
    private readonly db: IDatabase<IClient>;

    constructor(db: DBContainer) {
        this.db = db.database();
    }

    /**
     * Check if a token already exists in the database
     * Used during token generation to ensure uniqueness
     */
    async tokenExists(token: string): Promise<boolean> {
        const query = `
            SELECT EXISTS(
                SELECT 1
                FROM sources
                WHERE token = $[token]
            ) as exists;
        `;

        const result = await this.db.one<{ exists: boolean }>(query, { token });
        return result.exists;
    }

    /**
     * Get source by token (for authentication)
     * Excludes soft-deleted sources - deleted token immediately fails auth
     */
    async getByToken(token: string): Promise<Source | null> {
        const query = `
            SELECT *
            FROM sources
            WHERE token = $[token]
                AND deleted IS NULL
            LIMIT 1;
        `;

        return await this.db.oneOrNone<Source>(query, { token });
    }

    /**
     * Get source by ID
     * Excludes soft-deleted sources
     */
    async getById(id: string): Promise<Source | null> {
        const query = `
            SELECT *
            FROM sources
            WHERE id = $[id]
                AND deleted IS NULL;
        `;

        return await this.db.oneOrNone<Source>(query, { id });
    }

    /**
     * Get all sources with pagination and filters
     */
    async getAll(filters: SourceFilters): Promise<{ items: Source[]; count: number }> {
        const { page, limit, search, includeDeleted } = filters;
        const offset = (page - 1) * limit;

        const whereClauses: string[] = [];

        if (!includeDeleted) {
            whereClauses.push('deleted IS NULL');
        }

        if (search) {
            whereClauses.push(`(name ILIKE '%' || $/search/ || '%' OR email ILIKE '%' || $/search/ || '%')`);
        }

        const whereSQL = whereClauses.length > 0 ? 'WHERE ' + whereClauses.join(' AND ') : '';

        const itemsQuery = `
            SELECT *
            FROM sources
            ${whereSQL}
            ORDER BY created DESC
            LIMIT $/limit/ OFFSET $/offset/;
        `;

        const countQuery = `
            SELECT COUNT(*) as count
            FROM sources
            ${whereSQL};
        `;

        const [items, countResult] = await Promise.all([
            this.db.manyOrNone<Source>(itemsQuery, { ...filters, offset }),
            this.db.one<{ count: string }>(countQuery, filters)
        ]);

        return {
            items: items || [],
            count: parseInt(countResult.count, 10)
        };
    }

    /**
     * Create new source with token
     * Token must be generated by service before calling this method
     */
    async create(data: SourceCreateDTO & { token: string }): Promise<Source> {
        const query = `
            INSERT INTO sources (name, email, token)
            VALUES ($[name], $[email], $[token])
            RETURNING *;
        `;

        return await this.db.one<Source>(query, data);
    }

    /**
     * Update existing source
     * Uses COALESCE pattern - only updates provided fields
     */
    async update(id: string, data: SourceUpdateDTO | { token: string }): Promise<Source> {
        const query = `
            UPDATE sources
            SET
                name = COALESCE($[name], name),
                email = COALESCE($[email], email),
                token = COALESCE($[token], token)
            WHERE id = $[id]
                AND deleted IS NULL
            RETURNING *;
        `;

        return await this.db.one<Source>(query, { id, ...data });
    }

    /**
     * Soft delete source
     * Sets deleted timestamp - immediately fails authentication
     */
    async trash(id: string): Promise<Source> {
        const query = `
            UPDATE sources
            SET deleted = NOW()
            WHERE id = $[id]
                AND deleted IS NULL
            RETURNING *;
        `;

        return await this.db.one<Source>(query, { id });
    }

    /**
     * Hard delete source (use with caution)
     * Should only be used for cleanup/testing
     */
    async delete(id: string): Promise<void> {
        const query = `
            DELETE FROM sources
            WHERE id = $[id];
        `;

        await this.db.none(query, { id });
    }
}
