version: '3'
services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: automator-test
    environment:
      POSTGRES_USER: automator
      POSTGRES_PASSWORD: automator
      POSTGRES_SSL: on
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"  # Original Automator test port
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  automator_postgres_test_data:  # Unique volume name for Automator test